name: Centos8 Wheel Tester
on:
  push:
    branches:
      - master
  schedule:
    # Run nightly
    - cron: '0 0 * * *'

jobs:
  centos8_test:
    runs-on: ubuntu-latest
    container: centos:8
    strategy:
      fail-fast: false
      matrix:
        WHEEL:
          - PIP_NAME: numpy
            PKG_TEST: import numpy
          - PIP_NAME: cffi
            PKG_TEST: import cffi
          - PIP_NAME: cryptography
            PKG_TEST: |
              from cryptography.hazmat.backends.openssl.backend import backend
              print('Loaded: ' + backend.openssl_version_text())
              print('Linked Against: ' + backend._ffi.string(backend._lib.OPENSSL_VERSION_TEXT).decode('ascii'))
          - PIP_NAME: sqlalchemy
            PKG_TEST: import sqlalchemy
    name: "Centos8 for ${{ matrix.WHEEL.PIP_NAME }}"
    steps:
      - run: yum install -y python3-pip gcc
      - run: python3 -m pip install --upgrade pip
      - run: python3 -m pip install ${{ matrix.WHEEL.PIP_NAME }}
      - run: echo "${{ matrix.WHEEL.PKG_TEST }}" | python3
